### ISSUE TITLE
Wrong exposed ports for p2plisten?

### ISSUE THREAD

**Issue by MathCryptoDoc** [Nexus2k/polkadot-ansible#10]
When I use a nonstandard port for p2plisten, my node has very bad parachain performance with many missed votes. Changing the exposed port in [validator.yml](https://github.com/Nexus2k/polkadot-ansible/blob/master/roles/polkadot-validator/tasks/validator.yml) from
`- "{{ p2p_listen }}:30333"`
to
`- "{{ p2p_listen }}:{{ p2p_listen }}"`
seems to have fixed the issue. 

For some reason it still has `"30333/tcp": null` exposed -- I'm not sure if that is normal behavior.

**Comment by MathCryptoDoc** [comment]
I don't understand why the fix above gave me much better parachain performance. I should have also changed the p2p port with the `--port` flag, but I didn't. Maybe it was a fluke. I will try again for a next round of validating.

**Comment by Nexus2k** [comment]
Could be that other nodes have outgoing firewall rules that only send stuff to the standard port 30333

**Comment by Nexus2k** [comment]
Whoops, you're absolutely right... Will fix the issue asap.

**Comment by Nexus2k** [comment]
Thanks for your report @MathCryptoDoc I fixed the issue.

**Comment by Nexus2k** [comment]
> I should have also changed the p2p port with the --port flag, but I didn't.

So the --listen-address flag defined the container internal listening address. I did indeed mistakingly forward the external port to the static internal 30333 port instead of the actually container bound listen port.

**Comment by Nexus2k** [comment]
As correctly noticed polkadot binary seems to still always bind 30333. Which seems a bug, I've filed https://github.com/paritytech/polkadot/issues/5636 for that. Will update the code to make it work anyway for now.

**Comment by MathCryptoDoc** [comment]
To follow up: the current role that maps to internal port 30333 seems to work fine. During the last 4 parachain sessions, the node had good performance overall (no missed votes, plenty of era points like before). It was the only validator running on the node.
